[local]
localhost

[mongodb]
mongodb.daws80s.space

[redis]
redis.daws80s.space

[mysql]
mysql.daws80s.space

[rabbitmq]
rabbitmq.daws80s.space

[catalogue]
catalogue.daws80s.space

[user]
user.daws80s.space

[cart]
cart.daws80s.space

[shipping]
shipping.daws80s.space

[payment]
payment.daws80s.space

[frontend]
frontend.daws80s.space

[private-key-demo]
172.31.37.172